from django.db import models

class Employee(models.Model):
    org_id = models.CharField(max_length=10)
    org_name = models.CharField(max_length=255)
    scode = models.CharField(max_length=10)
    state = models.CharField(max_length=255)
    dcode = models.CharField(max_length=10)
    district = models.CharField(max_length=255)
    emp_office_loc = models.CharField(max_length=10)
    emp_loc_name = models.CharField(max_length=255)
    emp_org_dept_id = models.CharField(max_length=10)
    emp_department = models.CharField(max_length=255)
    emp_id = models.CharField(max_length=10)
    org_emp_code = models.CharField(max_length=10)
    emp_name = models.CharField(max_length=255)
    emp_cat = models.CharField(max_length=20)
    emp_dob = models.DateField(null=True, blank=True)
    gender = models.CharField(max_length=1, choices=[('M', 'Male'), ('F', 'Female')])
    emp_mail = models.EmailField()
    emp_mobile = models.CharField(max_length=15)
    att_date = models.DateField(null=True, blank=True)
    at_type = models.CharField(max_length=1, choices=[('C', 'Check-in'), ('O', 'Check-out')])
    in_device_id = models.CharField(max_length=10)
    in_time = models.DateTimeField(null=True, blank=True)
    in_device_type = models.CharField(max_length=1, choices=[('D', 'Device D'), ('T', 'Device T')])
    in_bio_device_id = models.CharField(max_length=20)
    in_device_mac = models.CharField(max_length=17)
    in_device_office_loc = models.CharField(max_length=255)
    in_device_entry_point = models.CharField(max_length=255)
    out_device_id = models.CharField(max_length=10)
    out_time = models.DateTimeField(null=True, blank=True)
    out_device_type = models.CharField(max_length=1, choices=[('D', 'Device D'), ('T', 'Device T')])
    out_bio_device_id = models.CharField(max_length=20)
    out_device_mac = models.CharField(max_length=17)
    out_device_office_loc = models.CharField(max_length=255)
    out_device_entry_point = models.CharField(max_length=255)
    stay_duration = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return self.emp_name
