# Generated by Django 4.2.5 on 2023-09-05 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.CharField(max_length=10)),
                ('org_name', models.CharField(max_length=255)),
                ('scode', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=255)),
                ('dcode', models.CharField(max_length=10)),
                ('district', models.CharField(max_length=255)),
                ('emp_office_loc', models.CharField(max_length=10)),
                ('emp_loc_name', models.CharField(max_length=255)),
                ('emp_org_dept_id', models.CharField(max_length=10)),
                ('emp_department', models.CharField(max_length=255)),
                ('emp_id', models.CharField(max_length=10)),
                ('org_emp_code', models.CharField(max_length=10)),
                ('emp_name', models.CharField(max_length=255)),
                ('emp_cat', models.CharField(max_length=20)),
                ('emp_dob', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('emp_mail', models.EmailField(max_length=254)),
                ('emp_mobile', models.CharField(max_length=15)),
                ('att_date', models.DateField()),
                ('at_type', models.CharField(choices=[('C', 'Check-in'), ('O', 'Check-out')], max_length=1)),
                ('in_device_id', models.CharField(max_length=10)),
                ('in_time', models.DateTimeField()),
                ('in_device_type', models.CharField(choices=[('D', 'Device D'), ('T', 'Device T')], max_length=1)),
                ('in_bio_device_id', models.CharField(max_length=20)),
                ('in_device_mac', models.CharField(max_length=17)),
                ('in_device_office_loc', models.CharField(max_length=255)),
                ('in_device_entry_point', models.CharField(max_length=255)),
                ('out_device_id', models.CharField(max_length=10)),
                ('out_time', models.DateTimeField()),
                ('out_device_type', models.CharField(choices=[('D', 'Device D'), ('T', 'Device T')], max_length=1)),
                ('out_bio_device_id', models.CharField(max_length=20)),
                ('out_device_mac', models.CharField(max_length=17)),
                ('out_device_office_loc', models.CharField(max_length=255)),
                ('out_device_entry_point', models.CharField(max_length=255)),
                ('stay_duration', models.IntegerField()),
            ],
        ),
    ]
