# Generated by Django 4.2.5 on 2023-09-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
