# Generated by Django 4.2.5 on 2023-09-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_employee_emp_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='att_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
