# Generated by Django 4.2.5 on 2023-09-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_alter_employee_att_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='in_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='stay_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
